---
name: 'Helm-chart-check'
description: 'Checking helm charts.'
author: 'ixxeL'
inputs:
  format:
    description: 'Format result. [parsable,standard,colored,github,auto]'
    required: false
    default: 'colored'
  strict:
    description: 'return non-zero exit code on warnings as well as errors.'
    required: false
    default: 'false'
  no-warnings:
    description: 'output only error level problems.'
    required: false
    default: 'false'
  config-file:
    description: 'path to a custom configuration.'
    required: false
    default: ''
  fix:
    description: 'will use yamlfix to fix YAML file errors.'
    required: false
    default: 'false'
  exit-zero:
    description: 'Force exit 0 code'
    required: false
    default: 'true'
  working-dir:
    description: 'file to scan'
    required: false
    default: './*.yaml'

runs:
  using: "composite"
  steps:
    - id: helm-chart-check
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Helm-chart check ] > Checking Helm chart.${BLANK}"
        echo -e "${CYAN}[ INFO ] > Helm version.${BLANK}"
        helm version --short
        echo -e "${YELLOW}[ EXECUTING ] > Checking helm chart ${{ inputs.working-dir }}.${BLANK}"


        if [[ -f ${{ inputs.working-dir }}/Chart.yaml ]]
        then
          echo -e "${CYAN}[ INFO ] > Chart.yaml file detected. Here is the file${BLANK}"
          yq e ${{ inputs.working-dir }}/Chart.yaml
          CHART_VERSION=$(yq e '.version' ${{ inputs.working-dir }}/Chart.yaml)
          echo -e "${CYAN}[ INFO ] > Chart version is --> ${CHART_VERSION}${BLANK}"
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m