---
name: Helm-chart-check-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ixxel/unit-tests-alpine:latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Helm chart checking
      uses: ixxeL-actions/helm-chart-check@main
      with:
        working-dir: './chart/postgresql'